name: Package Application

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, macos-15-intel]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build Python binary
        run: bash build.sh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'ui/.nvmrc'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install Node Dependencies
        run: npm install
        working-directory: ui

      - name: Build Nuxt
        run: npm run generate
        working-directory: ui

      - name: Build Electron App
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ui

      # - name: Upload Artifact  # For debugging
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-${{ matrix.os }}
      #     path: ui/out/make/**/*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ui/out/make/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
